# FreeCodeCamp - Machine Learning with Python

These are JulianNF's notes from following the [online certification](https://www.freecodecamp.org/learn/machine-learning-with-python). Feel free to benefit from them if you're studying on your own.

---


# Settings up in Windows

Getting tensorflow set up in VSCode (Windows machines) can be a bit more complicated than expected. We first need to get Anaconda installed:

1. Download the [Anaconda installer](https://www.anaconda.com/)
2. Run the installer
3. Open the Anaconda command prompt app from the start menu
4. Run `conda init powershell` to make the `conda` command present in the Powershell CLI
    - NB: You may need to also add the conda install folder to your PATHs. To do so, call `where conda` in the conda prompt to find the install location. Add the parent folder to your PATHs
5. (restart VSCode if it was already open)
6. Check that conda is now available in the VSCode Powershell terminal by calling `conda --version`
7. Install tensorflow with `conda install tensorflow`
8. Select the anaconda python interpreter for your file
    - If you're using a Jupyter notebook, you'll probably also need to set your cell kernel to your anaconda's Python.


In [1]:
import tensorflow as tf

# Intro to AI

**Artificial intelligence** (AI) is intelligence—perceiving, synthesizing, and inferring information—demonstrated by machines, as opposed to intelligence displayed by non-human animals and humans

Basically, automations that perform intellectual tasks

**Machine learning** is a subset of AI, where a ML model figures out “the rules” for solving a problem itself, without us telling it exactly what to do.

**Deep Learning / Neural Networks** is a further subset of machine learning. Though "inspired" by human thinking, it is not modeled after the human brain.

Neural networks have multiple layers, and are sometimes referred to as, “a multistage information extraction process”. In other words, input data is processed into “new” data by the algorithms, and this "new" data is then processed into further “new” data, and so and so forth until an output is provided.

## Data is critical for AI

The data used must provide both:

-   Quality
-   Quantity

For machine learning, data is structured as follows:

-   “features” are the input data
-   “labels” are the result / (expected) output

| feature | feature | ... | feature | label |
| ------- | ------- | --- | ------- | ----- |


# Intro to tensors in TensorFlow

A tensor is, “**A generalization of vectors and matrices to potentially higher dimensions**”

Why a vector? --> Because it can have lots of “dimensions”, each dimension being an additional related value.

In tensorflow, tensors are represented as n-dimensional arrays of base datatypes. Each tensor represents a partially defined computation that will eventually produce a value.

Each tensor has a certain "dimensionality", which reflects its complexity. The number of dimensions of a tensor is defined by its **rank** (aka **degree**). A tensor with one value has a rank/degree of zero (0), and is also called a “scalar”. For example:


In [4]:
stringTensor = tf.Variable("this is a string", tf.string)
numberTensor = tf.Variable(124, tf.int16)
floatTensor = tf.Variable(3.456, tf.float64)


We can **determine the rank/degree of any tensor with**...


In [5]:
tf.rank(stringTensor)


<tf.Tensor: shape=(), dtype=int32, numpy=0>

... and see that numpy reports a rank/degree of 0 for our scalar tensors.

Tensors with more than one dimension/rank/degree are known as vectors. For each nested layer, the tensor 'gains' one rank.


In [22]:
tensorWithRank1 = tf.Variable(
    ["Test", "Ok", "Tim"],
    tf.string
)
tensorWithRank2 = tf.Variable(
    [
        ["test", "ok"],
        ["test", "yes"],
        ["3rd", "element"],
    ],
    tf.string
)

# expect numpy = 2 because tensor has a list within a list
tf.rank(tensorWithRank2)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Tensor Shape

The shape of a tensor tells us the amount of elements that exist in each dimension of the tensor. For example:


In [26]:
tensorWithRank2.shape


TensorShape([3, 2])

## Changing a tensor's shape

The number of elements of a tensor is the product of the sizes of all its shapes (e.g. 3 lists x 2 elements/list = 6 elements).

If different tensors have the same number of elements, we can "reshape" the tensor (i.e. rearrange the elements). For example:


In [29]:
# tf.ones() creates a tensore with a shape [1,2,3] (total of 6 elements) where each element is a one
# tf.zeroes() also exists
tensor1 = tf.ones([1,2,3])
print(tensor1)

# reshape the tensor to a shape of [2,3,1] (total of siz elements)
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)

# -1 tells the tensor to calculate/infer the size of the dimension in that layer so that all the elements in the original tensor are accounted for --> in this case, it'll reshape the tensor to [3,2]
tensor3 = tf.reshape(tensor1, [3,-1])
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of tensors

There are many types of tensors. The most common ones are:

1. Variable
2. Constant
3. Placeholder
4. SparseTensor

With the exception of Variable tensors, the other tensors are immutable, in that their value cannot change during execution.


## Evaluating Tensors

Remember that tensors represent a partially complete computation. We will sometimes need to run a **session** in order to evaluate a tensor. There are many ways to get the value of a tensor, the simples being:


In [27]:
with tf.Session() as sess:
	tensor3.eval()

AttributeError: module 'tensorflow' has no attribute 'Session'