# NumPy UltraQuick Tutorial
Machine Learning prework from Google ([link](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/numpy_ultraquick_tutorial.ipynb?utm_source=mlcc&utm_campaign=colab-external&utm_medium=referral&utm_content=mlcc-prework&hl=en)).

In [1]:
import numpy as np

## Populate arrays with specific numbers
Call `np.array` to create a NumPy array with your own hand-picked values. For example, the following call to `np.array` creates an 8-element array:

In [2]:
one_dimensional_array = np.array([1.2,2.4,3.5,4.7,6.1,7.2,8.3,9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


You can also use `np.array` to create a 

---

two-dimensional array. To create a two-dimensional array specify an extra layer of square brackets. For example, the following call creates a 3x2 array:

In [4]:
two_dimensional_array = np.array(
	[
		[6,5],[11,7],[4,8]
	]
)
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


To populate an array with all zeroes, call `np.zeros`. To populate an array with all ones, call `np.ones`.

## Populate arrays with sequences of numbers

You can populate an array with a sequence of numbers:

In [5]:
sequence_of_integers = np.arange(5,12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


Notice that `np.arange` generates a sequence that includes the lower bound (5) but not the upper bound (12). 

## Populate arrays with random numbers

NumPy provides various functions to populate arrays with random numbers across certain ranges. For example, `np.random.randint` generates random integers between a low and high value. The following call populates a 6-element array with random integers between 50 and 100. 

In [9]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=6)
print(random_integers_between_50_and_100)

[82 85 90 62 97 94]


Note that the highest generated integer `np.random.randint` is one less than the `high` argument.

To create random floating-point values between 0.0 and 1.0, call `np.random.random`. For example:

In [16]:
random_floats_between_0_and_1 = np.random.random(6)
print(random_floats_between_0_and_1)

[0.48268155 0.58937372 0.93445975 0.34813662 0.61898667 0.47110486]


## Mathematical Operations on NumPy Operands

If you want to add or subtract two arrays, linear algebra requires that the two operands have the same dimensions. Furthermore, if you want to multiply two arrays, linear algebra imposes strict rules on the dimensional compatibility of operands. Fortunately, NumPy uses a trick called [**broadcasting**](https://developers.google.com/machine-learning/glossary/#broadcasting) to virtually expand the smaller operand to dimensions compatible for linear algebra. For example, the following operation uses broadcasting to add 2.0 to the value of every item in the array created in the previous code cell:

In [17]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.48268155 2.58937372 2.93445975 2.34813662 2.61898667 2.47110486]


The following operation also relies on broadcasting to multiply each cell in an array by 3:

In [18]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[246 255 270 186 291 282]


## Task 1: Create a Linear Dataset

Your goal is to create a simple dataset consisting of a single feature and a label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named `feature`.
2. Assign 15 values to a NumPy array named `label` such that:

```
   label = (3)(feature) + 4
```
For example, the first value for `label` should be:

```
  label = (3)(6) + 4 = 22
 ```

In [21]:
feature = np.arange(6, 21)
print(feature)

label = feature * 3 + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


## Task 2: Add Some Noise to the Dataset

To make your dataset a little more realistic, insert a little random noise into each element of the `label` array you already created. To be more precise, modify each value assigned to `label` by adding a *different* random floating-point value between -2 and +2. 

Don't rely on broadcasting. Instead, create a `noise` array having the same dimension as `label`.

In [79]:
noise = (np.random.random(15) * 4) - 2 # random floats between 0 and 4, then shifted down to between -2 and 2
print(noise)

label = label + noise
print(label)

[-1.00894144 -0.64332643  1.86185157  0.29792523 -1.52760414 -1.89371022
 -1.63234764 -1.67491413  0.48857296 -0.73229009 -0.11893728 -0.54232637
  0.02630017  1.11470536  0.86317118]
[ 2.64835827  0.37828701 -2.948968    0.10648013  2.53428061 -5.00650358
 -3.21935494  0.80357973  1.84805661 -1.53942844 -0.04785296 -1.79236309
  1.23737399  2.23854287  2.81200765]
