Machine Learning with Tensor and Python
===

These are JulianNF's notes from following [freecodecamp's online Machine Learning with Python certification](https://www.freecodecamp.org/learn/machine-learning-with-python), and supplemented by [Google's Tensorflow documentation](https://www.tensorflow.org/guide/tensor)

Feel free to benefit from them if you're studying on your own.

---

In [2]:
import tensorflow as tf
import numpy as np

# Intro to tensors in TensorFlow

A tensor is, “**A generalization of vectors and matrices to potentially higher dimensions**”

Why a vector? --> Because it can have lots of “dimensions”, each dimension being an additional related value.

In tensorflow, tensors are represented as n-dimensional arrays of base datatypes. Each tensor represents a partially defined computation that will eventually produce a value.

Each tensor has a certain "dimensionality", which reflects its complexity. The number of dimensions of a tensor is defined by its **rank** (aka **degree**). A tensor with one value has a rank/degree of zero (0), and is also called a “scalar”. For example:


In [3]:
stringTensor = tf.Variable("this is a string", tf.string)
numberTensor = tf.Variable(124, tf.int16)
floatTensor = tf.Variable(3.456, tf.float64)

## Dimension / Rank / Degree
Denotes the relative complexity of the structure of the tensor.

Tensors with two dimensions/ranks/degrees are known as a **vector**.

Tensors with 2 ranks have two axes and are referred to as a **"matrix"**. It's basically a nested list, and as such, a tensor can have an arbitrarily large number of axes.

![visualisations of 3-axis tensor](img\google-visualizing_tensors_with_multiple_axes.jpg)

We can determine the rank/degree of any tensor with `.rank()` and see that numpy reports a rank/degree of 0 for our scalar tensors:

In [4]:
print(tf.rank(stringTensor))


tensorWithRank1 = tf.Variable(
    ["Test", "Ok", "Tim"],
    tf.string
)
tensorWithRank2 = tf.Variable(
    [
        ["test", "ok"],
        ["test", "yes"],
        ["3rd", "element"],
    ],
    tf.string
)

# expect numpy = 2 because tensor has a list within a list
print(tf.rank(tensorWithRank2))


tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


## Getting the metadata of a tensor

Tensors have a number of methods that we can use to determine their shape, dimension/rank, etc:


In [6]:
rank_4_tensor = tf.zeros([3,2,4,5])

# Returning values:
print('Type of every element in tensor:', rank_4_tensor.dtype)
print('Number of axes/dimensions in tensor:', rank_4_tensor.ndim)
print('Elements in first axis of tensor:', rank_4_tensor.shape[0])
print('Elements in last axis of tensor:', rank_4_tensor.shape[-1])
print('Total number of elements in the tensor:', tf.size(rank_4_tensor).numpy())

# Returning objects:
print('\nType of every element in tensor:', tf.rank(rank_4_tensor))
print('Number of axes/dimensions in tensor:', tf.shape(rank_4_tensor.ndim))
print('Total number of elements in the tensor:', tf.size(rank_4_tensor))



Type of every element in tensor: <dtype: 'float32'>
Number of axes/dimensions in tensor: 4
Elements in first axis of tensor: 3
Elements in last axis of tensor: 5
Total number of elements in the tensor: 120

Type of every element in tensor: tf.Tensor(4, shape=(), dtype=int32)
Number of axes/dimensions in tensor: tf.Tensor([], shape=(0,), dtype=int32)
Total number of elements in the tensor: tf.Tensor(120, shape=(), dtype=int32)


## Converting a tensor to a list
As simple as:

In [8]:
rank_4_tensor.shape.as_list()

[3, 2, 4, 5]

## Tensor shape

Defines the size of each dimension of the tensor.

As a memory aid, to keep track of which axis contains what types of data, as tensors get more complex:

![typical tensor axis order](img\google-typical_tensor_axis_order.jpg)

### Changing a tensor's shape (aka reshaping)

The **size** of a tensor is the total number of elements in said tensor. The quickest way to think of it is as the product of the sizes of all its shapes (e.g. 3 lists x 2 elements/list = 6 elements).

If different tensors have the same number of elements, we can "reshape" the tensor (i.e. rearrange the elements). This operation is fast and cheap as the underlying data does not need to be duplicated. The data maintains its layout in memory, and a new tensor is created with the requested shape, pointing to the same data.

Typically the only reasonable use of `tf.reshape` is to combine or split adjacent axes (e.g. (3x2)x5 --> 3x(2x5)) (or add/remove 1s).


For example:


In [12]:
# tf.ones() creates a tensor with a shape [1,2,3] (total of 6 elements) where each element is a one
# tf.zeroes() also exists
tensor1 = tf.ones([1,2,3])
print(tensor1)

# reshape the tensor to a shape of [2,3,1] (total elements = original size of tensor)
tensor2 = tf.reshape(tensor1, [2,3,1])
print(tensor2)

# -1 tells the tensor to calculate/infer the size of the dimension in that layer so that all the elements in the original tensor are accounted for --> in this case, it'll reshape the tensor to [3,2]
tensor3 = tf.reshape(tensor1, [3,-1])
print(tensor3)

# Flatten a tensor entirely to one vector, which will show the order of the elements in memory:
tensor3 = tf.reshape(tensor1, [-1])
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)


## Converting tensors to numpy arrays

To convert a tensor to a numpy array, simply use `np.array` or `tensor/numpy()`:

In [10]:
numpyArray1 = np.array(tensor2)
print(numpyArray1)

numpyArray2 = tensor2.numpy()
print(numpyArray2)


[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


## Performing math on tensors

Like with regular arrays, mathematical operations can be performed on tensors and their elements:

In [16]:
firstTensor = tf.constant(
    [
        [1, 2],
        [3, 4]
    ]
)
secondTensor = tf.constant(
    [
        [1, 1],
        [1, 1]
    ]
)

print(tf.add(firstTensor, secondTensor), '\n')
print(tf.multiply(firstTensor, secondTensor), '\n')
print(tf.matmul(firstTensor, secondTensor), '\n')

print(firstTensor + secondTensor, '\n') # element-wise addition
print(firstTensor * secondTensor, '\n') # element-wise multiplication
print(firstTensor @ secondTensor, '\n') # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



### Operations (aka Ops)
Tensors are used in all kinds of operations (aka **Ops**):

In [19]:
anotherTensor = tf.constant(
	[
		[4.0, 5.0],
		[10.0, 1.0]
	]
)

#  Find the largest value:
print(tf.reduce_max(anotherTensor))
# Find the index of the largest value:
print(tf.math.argmax(anotherTensor))
# Compute the softmax:
print(tf.nn.softmax(anotherTensor))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


Note that tensor also refers to method such as `reshape` as an operation.

## Broadcasting
Like with Numpy arrays, when performing matrix operations, under certain circumstances, Tensorflow will expand the tensors so that their column and row sizes match, in order to allow the math operation to work

Most of the time, broadcasting is both time and space efficient, as the broadcast operation never materializes the expanded tensors in memory. Note however that `tf.broadcast_to()` does nothing special to save memory, and materialzies the tensor.

🧠📖 For more info on broadcasting in Python, see Jake VanderPlas' book [_Python Data Science Handbook_](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html).

In [28]:
scalar = tf.constant(3)
vector1 = tf.constant([1,2,3])
vector2 = tf.constant([3,3,3]) # equivalent to 'scalar' if it was broadcast to the size of vector1

print(tf.multiply(vector1, scalar))
print(vector1 * scalar)
print(vector1 * vector2)

# Another example:
vector1a = tf.reshape(vector1, [3,1])
print('\n', vector1a)
vector2a = tf.range(1,5)
print(vector2a)
print(tf.multiply(vector1a, vector2a))


tf.Tensor([3 6 9], shape=(3,), dtype=int32)
tf.Tensor([3 6 9], shape=(3,), dtype=int32)
tf.Tensor([3 6 9], shape=(3,), dtype=int32)

 tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


## Accessing data in tensors

Tensor data is zero-index and behaves like a Python list. To access the desired data, use indeces as you would in Python, including using `:` for slicing:

In [5]:
# Vectors:
simpleTensor = tf.constant([0,1,2,3,5,8,21,34])
print(simpleTensor[0].numpy())
print(simpleTensor[4].numpy())
print(simpleTensor[-2].numpy())

print(simpleTensor[:4].numpy())
print(simpleTensor[4:].numpy())
print(simpleTensor[6:8].numpy())
print(simpleTensor[3:9:3].numpy())
print(simpleTensor[3:9:-1].numpy())
print(simpleTensor[::2].numpy())

# 2nd-degree matrices:
rank_2_tensor = tf.constant(
    [
        [3.5, 6.2],
        [1, 2]
    ]
)

print('\n')
print(rank_2_tensor[0, 1].numpy())
print(rank_2_tensor[0, :].numpy())
print(rank_2_tensor[-1, :].numpy())
print(rank_2_tensor[1, -1].numpy())

# 3rd-degree matrices:
rank_3_tensor = tf.constant(
    [
        [
            [3.5, 6.2],
            [-3, 55.6]
        ],
        [
            [12, 432],
            [1, 212.5]
        ],
        [
            [16, 78],
            [66, 95.687]
        ]
    ]
)

print('\n')
print(rank_3_tensor[:, :, 1].numpy())
print(rank_3_tensor[0, 1, 1].numpy())
print(rank_3_tensor[0, :, :].numpy())
print(rank_3_tensor[-1, 0, :].numpy())
print(rank_3_tensor[1, -1, -1].numpy())


0
5
21
[0 1 2 3]
[ 5  8 21 34]
[21 34]
[ 3 21]
[]
[ 0  2  5 21]


6.2
[3.5 6.2]
[1. 2.]
2.0


[[  6.2    55.6  ]
 [432.    212.5  ]
 [ 78.     95.687]]
55.6
[[ 3.5  6.2]
 [-3.  55.6]]
[16. 78.]
212.5


## Using other objects with tensor methods

Typically, Tensorflow can handle using valid inputs that are not tensors. Note that if you don't pass a datatype (optional), Tensor will infer a datatype that works for all the data
- python integers --> tf.int32
- python floats --> tf.float32

↗️ Most (but not all) ops call `tf.convert_to_tensor` on non-tensor arguments. There's a registry of conversions and most object classes will convert automatically. To add you own types, check out `tf.register_tensor_conversion_function`.

In [13]:
tf.convert_to_tensor([1,2,3])
tf.convert_to_tensor([1,2,3], dtype=tf.float64)
tf.reduce_max([1,2,3])
tf.reduce_max(np.array([1,2,3]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## Casting tensor element datatypes

You can cast the `dtype` of a tensor to another datatype:

In [18]:
f64_tensor = tf.constant([2.23456789, 3.3, 4.4], dtype=tf.float64)
print(f64_tensor)
f16_tensor = tf.cast(f64_tensor, dtype=tf.float16)
print(f16_tensor)

u8_tensor = tf.cast(f16_tensor, dtype=tf.uint8) # lose all decimal precision
print(u8_tensor)

tf.Tensor([2.23456789 3.3        4.4       ], shape=(3,), dtype=float64)
tf.Tensor([2.234 3.3   4.4  ], shape=(3,), dtype=float16)
tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


## Types of tensors

There are many types of tensors. The most common ones are:

1. Variable
2. Constant
3. Placeholder
4. SparseTensor

With the exception of Variable tensors, the other tensors are immutable, in that their value cannot change during execution.

The base `tf.Tensor` class requires tensors to be "rectangular", that is, every element along an axis must be the same size (i.e. type). Nevertheless, there are some specialized tensors that can handle different shapes:
- ragged tensors
- sparse tensors

### Ragged Tensors

Tensors with inconsistent axis sizes (at the same parent level) as referred to as "**ragged**". When working with such data, use `tf.ragged.RaggedTensor`.

![ragged tensor depiction](img\google-ragged_tensor_image.jpg)

In [33]:
ragged_list = [
	[0,1,2,3],
	[4,5],
	[6,7,8],
	[9]
]

try:
	tensor = tf.constant(ragged_list)
except Exception as e:
	print(f"{type(e).__name__}: {e}")

ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)
print(ragged_tensor.shape) # note how the length of the second axis is unknown

ValueError: Can't convert non-rectangular Python sequence to Tensor.
<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>
(4, None)


### String Tensors

Strings in Tensorflow are stored as variable-length byte arrays (not a unicode string).

It's important to not that string tensors are atomic -- you cannot access characters via index. As such, **the length of the string is not one of the axes of the tensor**. In order words, when considering strings, Tensor ignores the length of each entry.

See `tf.strings` for functions to manipulate strings in Tensor.

A string tensor can be split into more tensors, but be aware that this will likely result in a ragged tensor, as the lengths and splitting-characters of each string might not be the same across the strings in the original tensor.

In [3]:
string_tensor = tf.constant(
	[
		"Gray wolf pup",
		"Chocolate lab",
		"Kangaroo"
	]
)

print(string_tensor) # note how no length is reported in the output

tf.Tensor([b'Gray wolf pup' b'Chocolate lab' b'Kangaroo'], shape=(3,), dtype=string)


In [4]:
print(tf.strings.split(string_tensor, sep=''))

<tf.RaggedTensor [[b'Gray', b'wolf', b'pup'], [b'Chocolate', b'lab'], [b'Kangaroo']]>


### Sparse Tensors

![sparse tensor image](img\google-sparse_tensor_image.png)

Sometimes the data is missing lots of entries. For this, we can use sparse tensors. These store values by index, rather than having a bunch of empty spots in memory.

In [46]:
sparse_tensor = tf.sparse.SparseTensor(
	indices=[
		[0,0],
		[1,2]
	],
	values= [1, 2 ],
	dense_shape=[3,4]
)
# convert sparse tensor to dense (i.e. full) and print
print(tf.sparse.to_dense(sparse_tensor))

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


## Evaluating Tensors

Remember that tensors represent a partially complete computation. We will sometimes need to run a **session** in order to evaluate a tensor. There are many ways to get the value of a tensor, the simples being:


In [11]:
with tf.Session() as sess:
	tensor3.eval()

AttributeError: module 'tensorflow' has no attribute 'Session'